name: MSBuild

on:
  pull_request:
    branches:
      - 'master'

env:
  SOLUTION_FILE_PATH: CP_Main_10.sln
  VERSION_FILENAME: 3_24_5_0  
  VERSION_DOT_FILENAME: 3.24.5.0  

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      #- name: Build 32bit
      #  run: msbuild CP_Main_10.sln /p:Configuration=Release /p:Platform=Win32
        
      #- name: Build 64bit
      #  run: msbuild CP_Main_10.sln /p:Configuration=Release /p:Platform=x64  
        
      - name: Compile 32bit installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: DittoSetup\DittoSetup_10.iss
          options: /F"DittoSetup_${{env.VERSION_FILENAME}}"
          
      - name: Compile 64bit installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: DittoSetup\DittoSetup_10.iss
          options: /F"DittoSetup_64bit__${{env.VERSION_FILENAME}}" "/dbit64=1"
    
    # - name: Build Setup
      # run: |
        # "C:\Program Files (x86)\Inno Setup 6\iscc.exe" /F"DittoSetup" DittoSetup\DittoSetup_10.iss
      # shell: cmd
    
    # - name: Upload
      # uses: actions/upload-artifact@v2
      # with:
        # name: Install
        # path: DittoSetup\Output\DittoSetup.exe
