name: MSBuild

on:
  pull_request:
    branches: [ "moved-files" ]

env:
  SOLUTION_FILE_PATH: CP_Main_10.sln 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build
        run: msbuild CP_Main_10.sln /p:Configuration=Release /p:Platform=Win32
    
    # - name: Build Setup
      # run: |
        # "C:\Program Files (x86)\Inno Setup 6\iscc.exe" /F"DittoSetup" DittoSetup\DittoSetup_10.iss
      # shell: cmd
    
    # - name: Upload
      # uses: actions/upload-artifact@v2
      # with:
        # name: Install
        # path: DittoSetup\Output\DittoSetup.exe
