name: MSBuild

on:
  pull_request:
    branches:
      - 'master'

env:
  SOLUTION_FILE_PATH: CP_Main_10.sln
  VERSION_FILENAME: 3_24_5_0  
  VERSION_DOT_FILENAME: 3.24.5.0  

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      #- name: Restore NuGet packages
      #  working-directory: ${{env.GITHUB_WORKSPACE}}
      #  run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      #- name: Build 32bit
      #  run: msbuild CP_Main_10.sln /p:Configuration=Release /p:Platform=Win32
        
      #- name: Build 64bit
      #  run: msbuild CP_Main_10.sln /p:Configuration=Release /p:Platform=x64  
        
      - name: Compile 32bit installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: DittoSetup\DittoSetup_10.iss
          options: /F"DittoSetup_${{env.VERSION_FILENAME}}"
          
      - name: Compile 64bit installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: DittoSetup\DittoSetup_10.iss
          options: /F"DittoSetup_64bit_${{env.VERSION_FILENAME}}" "/dbit64=1"
          
      - name: Build Portable
        run: |
            DittoSetup\BuildPortableZIP.bat "DittoPortable_${{env.VERSION_FILENAME}}" bit32
            DittoSetup\BuildPortableZIP.bat "DittoPortable_64bit_${{env.VERSION_FILENAME}}" bit64
            
      - name: Zip Debug Files
        run: |
            7z a DittoSetup\output\DittoDebug_${{env.VERSION_FILENAME}}.7z *.pdb -r
            7z a DittoSetup\output\DittoDebug_${{env.VERSION_FILENAME}}.7z *.map -r
            
      - name: Choco
        shell: pwsh
        run: |
            (Get-Content 'DittoSetup\Chocolatey\ditto.nuspec' -Raw).Replace("%version%", "$($env:VERSION_DOT_FILENAME)") | Out-File 'DittoSetup\Chocolatey\ditto.nuspec'
            copy DittoSetup\Output\DittoSetup_${{env.VERSION_FILENAME}}.exe DittoSetup\Chocolatey\tools\DittoSetup_${{env.VERSION_FILENAME}}.exe
            copy DittoSetup\Output\DittoSetup_64bit_${{env.VERSION_FILENAME}}.exe DittoSetup\Chocolatey\tools\DittoSetup_64bit_${{env.VERSION_FILENAME}}.exe
            cd DittoSetup\Chocolatey
            echo ${{secrets.CHOCO_API_KEY}} | sed 's/./& /g'
            echo "push --key ${{ secrets.CHOCO_API_KEY}} --source https://push.chocolatey.org/"
            choco pack     
            choco push --key ${{ secrets.CHOCO_API_KEY}} --source https://push.chocolatey.org/
            cd ..
            cd ..
    
    # - name: Build Setup
      # run: |
        # "C:\Program Files (x86)\Inno Setup 6\iscc.exe" /F"DittoSetup" DittoSetup\DittoSetup_10.iss
      # shell: cmd
    
    # - name: Upload
      # uses: actions/upload-artifact@v2
      # with:
        # name: Install
        # path: DittoSetup\Output\DittoSetup.exe

