name: MSBuild

on:
  push:
    branches:
      - signpath
    paths-ignore:
      - '**/README.md'

env:
  SOLUTION_FILE_PATH: CP_Main_10.sln

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
               
      - name: Set the value
        run: |
            echo "VERSION_FILENAME=3_25_100_0" | Out-File -FilePath $env:GITHUB_ENV -Append
            echo "VERSION_DOT_FILENAME=3.25.100.0" | Out-File -FilePath $env:GITHUB_ENV -Append
            
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}
        
      - name: Build 64bit
        run: msbuild CP_Main_10.sln /p:Configuration=Release /p:Platform=x64
        
      - name: Set Versions
        run: |
            DittoSetup\rcedit-x64 Release64\Ditto.exe --set-file-version ${{env.VERSION_DOT_FILENAME}} --set-product-version ${{env.VERSION_DOT_FILENAME}}

      - name: 64bit installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: DittoSetup\DittoSetup_10.iss
          options: /F"DittoSetup_${{env.VERSION_FILENAME}}" "/dbit64=1"

      - name: upload-unsigned-installer
        id: upload-unsigned-installer
        uses: actions/upload-artifact@v4
        with: 
          path: DittoSetup\output\DittoSetup_${{env.VERSION_FILENAME}}.exe

      - id: optional_step_id
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: 'fcf33ea4-4343-46b3-be50-f8fe64e1a900'
          project-slug: 'Ditto'
          artifact-configuration-slug: 'Installer'
          signing-policy-slug: 'test-signing'
          github-artifact-id: '${{ steps.upload-unsigned-installer.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: '/DittoSetup/outputSigned'

